window.listeHuilesMotherTree = [
    {
        nom: "Huile d’abyssinie",
        categorie: "douce",
        sapNaoh: 0.168,
        sapKoh: 0.236,
        iode: 98.0,
        ins: 70.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 2.0,
        stearique: 1.0,
        ricinoleique: 0.0,
        oleique: 12.0,
        linoleique: 10.0,
        linolenique: 2.0,
        commentaire: "Sources : SoapCalc, FNWL, AAK. Profil riche en érucique et gadoleique exclu selon protocole. Données croisées.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre d’amande",
        categorie: "douce",
        sapNaoh: 0.138,
        sapKoh: 0.194,
        iode: 60.0,
        ins: 110.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 5.0,
        stearique: 9.0,
        ricinoleique: 0.0,
        oleique: 60.0,
        linoleique: 25.0,
        linolenique: 0.5,
        commentaire: "Source : FNWL. Données homogènes avec huiles similaires (amande douce, noyau de pêche). Peu documenté, mais structure logique.",
        fiabilite: "moyenne"
    },
    {
        nom: "Huile d’amande douce",
        categorie: "douce",
        sapNaoh: 0.136,
        sapKoh: 0.191,
        iode: 98.0,
        ins: 76.0,
        laurique: 0.0,
        myristique: 0.1,
        palmitique: 6.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 66.0,
        linoleique: 25.0,
        linolenique: 0.5,
        commentaire: "Sources : SoapCalc, FNWL, MakingCosmetics. Données très cohérentes et largement documentées.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile d’andiroba",
        categorie: "douce",
        sapNaoh: 0.188,
        sapKoh: 0.264,
        iode: 68.0,
        ins: 120.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 28.0,
        stearique: 8.0,
        ricinoleique: 0.0,
        oleique: 51.0,
        linoleique: 9.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, Jedwards. Acide palmitique élevé. Propriétés cicatrisantes traditionnelles.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de noyau d’abricot",
        categorie: "douce",
        sapNaoh: 0.195,
        sapKoh: 0.274,
        iode: 100.0,
        ins: 91.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 6.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 66.0,
        linoleique: 27.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL, MakingCosmetics. Profil très similaire à l’amande douce. Données fiables.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile d’argan",
        categorie: "douce",
        sapNaoh: 0.191,
        sapKoh: 0.268,
        iode: 95.0,
        ins: 95.0,
        laurique: 0.0,
        myristique: 1.0,
        palmitique: 14.0,
        stearique: 5.0,
        ricinoleique: 0.0,
        oleique: 46.0,
        linoleique: 34.0,
        linolenique: 1.0,
        commentaire: "Sources : SoapCalc, AAK, FNWL. Composition bien documentée et stable.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre d’avocat",
        categorie: "douce",
        sapNaoh: 0.187,
        sapKoh: 0.262,
        iode: 67.0,
        ins: 120.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 21.0,
        stearique: 10.0,
        ricinoleique: 0.0,
        oleique: 53.0,
        linoleique: 6.0,
        linolenique: 2.0,
        commentaire: "Source : FNWL. Profil légèrement différent de l’huile d’avocat, plus structurant. Données cohérentes.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile d’avocat",
        categorie: "douce",
        sapNaoh: 0.186,
        sapKoh: 0.261,
        iode: 86.0,
        ins: 99.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 20.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 58.0,
        linoleique: 12.0,
        linolenique: 1.0,
        commentaire: "Sources : SoapCalc, FNWL, AAK. Profil stable, très utilisé en cosmétique.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de babassu",
        categorie: "dure",
        sapNaoh: 0.245,
        sapKoh: 0.344,
        iode: 15.0,
        ins: 230.0,
        laurique: 50.0,
        myristique: 20.0,
        palmitique: 11.0,
        stearique: 4.0,
        ricinoleique: 0.0,
        oleique: 10.0,
        linoleique: 0.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL, MakingCosmetics. Similaire à l’huile de coco, mais plus doux en SAF.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de baobab",
        categorie: "douce",
        sapNaoh: 0.200,
        sapKoh: 0.281,
        iode: 75.0,
        ins: 125.0,
        laurique: 0.0,
        myristique: 1.0,
        palmitique: 24.0,
        stearique: 4.0,
        ricinoleique: 0.0,
        oleique: 37.0,
        linoleique: 28.0,
        linolenique: 2.0,
        commentaire: "Sources : FNWL, Jedwards, AAK. Très bon équilibre douceur/nutrition. Données croisées.",
        fiabilite: "confirmée"
    },
    {
        nom: "Cire d’abeille",
        categorie: "dure",
        sapNaoh: 0.094,
        sapKoh: 0.132,
        iode: 10.0,
        ins: 84.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 0.0,
        stearique: 0.0,
        ricinoleique: 0.0,
        oleique: 0.0,
        linoleique: 0.0,
        linolenique: 0.0,
        commentaire: "Source : SoapCalc. Utilisée en faible pourcentage comme durcisseur. Pas de profil AG exploitable.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de cumin noir (nigella sativa)",
        categorie: "douce",
        sapNaoh: 0.195,
        sapKoh: 0.274,
        iode: 133.0,
        ins: 62.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 13.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 22.0,
        linoleique: 60.0,
        linolenique: 1.0,
        commentaire: "Sources : FNWL, MakingCosmetics. Iode élevé, usage recommandé en petite quantité. Données fiables.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de pépins de cassis",
        categorie: "douce",
        sapNaoh: 0.190,
        sapKoh: 0.267,
        iode: 178.0,
        ins: 12.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 6.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 13.0,
        linoleique: 46.0,
        linolenique: 18.0,
        commentaire: "Sources : FNWL, MakingCosmetics. Très riche en AG polyinsaturés, usage réservé aux soins ciblés. Instable en SAF.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de bourrache",
        categorie: "douce",
        sapNaoh: 0.190,
        sapKoh: 0.267,
        iode: 135.0,
        ins: 55.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 10.0,
        stearique: 4.0,
        ricinoleique: 0.0,
        oleique: 20.0,
        linoleique: 43.0,
        linolenique: 5.0,
        commentaire: "Sources : SoapCalc, FNWL. Forte proportion d'AG sensibles, limiter l’usage à de faibles pourcentages.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de noix du Brésil",
        categorie: "douce",
        sapNaoh: 0.190,
        sapKoh: 0.267,
        iode: 100.0,
        ins: 90.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 13.0,
        stearique: 11.0,
        ricinoleique: 0.0,
        oleique: 39.0,
        linoleique: 36.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, MakingCosmetics. Bon équilibre entre douceur et nutrition. Données fiables.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de graine de brocoli",
        categorie: "douce",
        sapNaoh: 0.172,
        sapKoh: 0.241,
        iode: 105.0,
        ins: 67.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 3.0,
        stearique: 1.0,
        ricinoleique: 0.0,
        oleique: 14.0,
        linoleique: 11.0,
        linolenique: 9.0,
        commentaire: "Sources : FNWL, Lotioncrafter. Huile légère, riche en AG insaturés. Usage à faible dose recommandé.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de camélia (graines de thé)",
        categorie: "dure",
        sapNaoh: 0.193,
        sapKoh: 0.271,
        iode: 78.0,
        ins: 115.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 9.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 77.0,
        linoleique: 8.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL. Très riche en acide oléique, proche de l’olive. Bonne stabilité en SAF.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de graine de carotte, pressée à froid",
        categorie: "douce",
        sapNaoh: 0.144,
        sapKoh: 0.202,
        iode: 56.0,
        ins: 0.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 4.0,
        stearique: 0.0,
        ricinoleique: 0.0,
        oleique: 80.0,
        linoleique: 13.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, MakingCosmetics. Huile précieuse et peu commune, très stable. Profil oléique dominant.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de ricin",
        categorie: "douce",
        sapNaoh: 0.180,
        sapKoh: 0.253,
        iode: 86.0,
        ins: 95.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 0.0,
        stearique: 0.0,
        ricinoleique: 90.0,
        oleique: 4.0,
        linoleique: 4.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL, AAK. Très riche en acide ricinoléique. Incontournable pour la mousse crémeuse.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de noyau de cerise (prunus avium)",
        categorie: "douce",
        sapNaoh: 0.190,
        sapKoh: 0.267,
        iode: 128.0,
        ins: 62.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 8.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 31.0,
        linoleique: 45.0,
        linolenique: 2.0,
        commentaire: "Sources : FNWL, MakingCosmetics. AG polyinsaturés élevés, bon adoucissant. Fragile en SAF.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de noyau de cerise (prunus cerasus)",
        categorie: "douce",
        sapNaoh: 0.192,
        sapKoh: 0.269,
        iode: 118.0,
        ins: 74.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 6.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 50.0,
        linoleique: 40.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL. Variante acide plus stable que prunus avium, riche en oléique. Moins documentée.",
        fiabilite: "moyenne"
    },
    {
        nom: "Beurre de cacao",
        categorie: "dure",
        sapNaoh: 0.194,
        sapKoh: 0.272,
        iode: 37.0,
        ins: 157.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 28.0,
        stearique: 33.0,
        ricinoleique: 0.0,
        oleique: 35.0,
        linoleique: 3.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, AAK, FNWL. Très structurant, excellent pour dureté et texture finale. Données très cohérentes.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de coco, 76°F",
        categorie: "dure",
        sapNaoh: 0.257,
        sapKoh: 0.361,
        iode: 10.0,
        ins: 258.0,
        laurique: 48.0,
        myristique: 19.0,
        palmitique: 9.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 8.0,
        linoleique: 2.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL. Forte action moussante et nettoyante. Indispensable mais à doser prudemment (≤20%).",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de coco, 92°F",
        categorie: "dure",
        sapNaoh: 0.257,
        sapKoh: 0.361,
        iode: 3.0,
        ins: 258.0,
        laurique: 48.0,
        myristique: 19.0,
        palmitique: 9.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 8.0,
        linoleique: 2.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, MakingCosmetics. Identique à la version 76°F mais plus stable à température ambiante élevée. Moins disponible.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de café vert",
        categorie: "dure",
        sapNaoh: 0.185,
        sapKoh: 0.260,
        iode: 85.0,
        ins: 100.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 38.0,
        stearique: 8.0,
        ricinoleique: 0.0,
        oleique: 9.0,
        linoleique: 39.0,
        linolenique: 2.0,
        commentaire: "Source : FNWL. Profil très saturé, bonne structure mais instable à l’oxydation. À combiner avec antioxydants.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de café torréfié",
        categorie: "dure",
        sapNaoh: 0.180,
        sapKoh: 0.253,
        iode: 87.0,
        ins: 93.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 40.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 8.0,
        linoleique: 38.0,
        linolenique: 2.0,
        commentaire: "Sources : FNWL, MakingCosmetics. Similaire au café vert mais plus oxydé. Senteur plus marquée, usage ponctuel.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de cohune",
        categorie: "dure",
        sapNaoh: 0.205,
        sapKoh: 0.288,
        iode: 30.0,
        ins: 175.0,
        laurique: 51.0,
        myristique: 13.0,
        palmitique: 8.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 18.0,
        linoleique: 3.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FAO. Huile tropicale rare, très proche du babassu ou coco. Moussante et nettoyante.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de maïs",
        categorie: "douce",
        sapNaoh: 0.192,
        sapKoh: 0.270,
        iode: 117.0,
        ins: 69.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 12.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 32.0,
        linoleique: 51.0,
        linolenique: 1.0,
        commentaire: "Sources : SoapCalc, USDA FDC. Très riche en AG polyinsaturés, faible stabilité. Usage limité en SAF.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de coton",
        categorie: "douce",
        sapNaoh: 0.194,
        sapKoh: 0.272,
        iode: 108.0,
        ins: 89.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 13.0,
        stearique: 13.0,
        ricinoleique: 0.0,
        oleique: 18.0,
        linoleique: 52.0,
        linolenique: 1.0,
        commentaire: "Sources : FAO, SoapCalc. Riche en linoleique mais mieux équilibrée que le maïs. À stabiliser par synergie.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de pépins de canneberge",
        categorie: "douce",
        sapNaoh: 0.190,
        sapKoh: 0.267,
        iode: 150.0,
        ins: 40.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 6.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 23.0,
        linoleique: 37.0,
        linolenique: 32.0,
        commentaire: "Source : FNWL. Exceptionnellement riche en AG oméga-3, très instable. À réserver pour ajouts post-saponification.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre de cupuaçu",
        categorie: "dure",
        sapNaoh: 0.192,
        sapKoh: 0.270,
        iode: 39.0,
        ins: 153.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 8.0,
        stearique: 35.0,
        ricinoleique: 0.0,
        oleique: 42.0,
        linoleique: 2.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, AAK. Beurre très structurant et nourrissant, alternative douce au karité ou cacao.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile d’onagre",
        categorie: "douce",
        sapNaoh: 0.190,
        sapKoh: 0.267,
        iode: 160.0,
        ins: 30.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 6.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 8.0,
        linoleique: 80.0,
        linolenique: 9.0,
        commentaire: "Sources : SoapCalc, MakingCosmetics. Profil thérapeutique remarquable, mais instabilité majeure. Ajout post-SAF recommandé.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de pépins de raisin",
        categorie: "douce",
        sapNaoh: 0.181,
        sapKoh: 0.254,
        iode: 131.0,
        ins: 66.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 8.0,
        stearique: 4.0,
        ricinoleique: 0.0,
        oleique: 20.0,
        linoleique: 68.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL. Huile légère et émolliente, mais très oxydable. Mieux en ajout à froid.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de noisette",
        categorie: "douce",
        sapNaoh: 0.195,
        sapKoh: 0.274,
        iode: 97.0,
        ins: 94.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 5.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 75.0,
        linoleique: 10.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL. Très stable et pénétrante, excellente alternative à l’olive pour peau mixte.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de chanvre",
        categorie: "douce",
        sapNaoh: 0.193,
        sapKoh: 0.271,
        iode: 165.0,
        ins: 39.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 6.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 12.0,
        linoleique: 57.0,
        linolenique: 21.0,
        commentaire: "Sources : SoapCalc, FNWL. Très riche en AG essentiels. Usage SAF limité à faibles pourcentages (<15 %).",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre d’illipé",
        categorie: "dure",
        sapNaoh: 0.185,
        sapKoh: 0.260,
        iode: 33.0,
        ins: 152.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 17.0,
        stearique: 45.0,
        ricinoleique: 0.0,
        oleique: 35.0,
        linoleique: 0.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, AAK. Beurre ultra-structurant. Alternative très stable au karité, très durcissant.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de jojoba",
        categorie: "douce",
        sapNaoh: 0.092,
        sapKoh: 0.129,
        iode: 83.0,
        ins: 11.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 2.0,
        stearique: 0.5,
        ricinoleique: 0.0,
        oleique: 70.0,
        linoleique: 10.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL. Cire liquide, non saponifiable en totalité. Idéal en surgras pour peau sèche.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre de kokum",
        categorie: "dure",
        sapNaoh: 0.190,
        sapKoh: 0.267,
        iode: 35.0,
        ins: 155.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 4.0,
        stearique: 56.0,
        ricinoleique: 0.0,
        oleique: 36.0,
        linoleique: 1.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, MakingCosmetics. Très dur, très stable. Excellente alternative végétale au beurre de cacao.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre de kpangnan",
        categorie: "dure",
        sapNaoh: 0.191,
        sapKoh: 0.268,
        iode: 42.0,
        ins: 149.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 6.0,
        stearique: 44.0,
        ricinoleique: 0.0,
        oleique: 49.0,
        linoleique: 1.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, AAK. Beurre africain rare, proche du karité. Bon compromis dureté/souplesse.",
        fiabilite: "confirmée"
    }
,
    {
        nom: "Huile de baie de laurier",
        categorie: "dure",
        sapNaoh: 0.198,
        sapKoh: 0.278,
        iode: 74.0,
        ins: 124.0,
        laurique: 25.0,
        myristique: 1.0,
        palmitique: 15.0,
        stearique: 1.0,
        ricinoleique: 0.0,
        oleique: 31.0,
        linoleique: 26.0,
        linolenique: 1.0,
        commentaire: "Sources : FNWL, SoapCalc. Incontournable du savon d’Alep. Très purifiante mais difficile à obtenir pure.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de graine de luffa",
        categorie: "douce",
        sapNaoh: 0.187,
        sapKoh: 0.262,
        iode: 108.0,
        ins: 79.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 9.0,
        stearique: 18.0,
        ricinoleique: 0.0,
        oleique: 30.0,
        linoleique: 47.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL. Profil original et stable. Apporte douceur et texture dense, bonne alternative au coton.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre de macadamia",
        categorie: "dure",
        sapNaoh: 0.188,
        sapKoh: 0.264,
        iode: 70.0,
        ins: 118.0,
        laurique: 0.0,
        myristique: 1.0,
        palmitique: 6.0,
        stearique: 12.0,
        ricinoleique: 0.0,
        oleique: 56.0,
        linoleique: 3.0,
        linolenique: 1.0,
        commentaire: "Sources : FNWL, MakingCosmetics. Très nourrissant, texture crémeuse. Bonne tenue en SAF, proche de l'huile.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de macadamia",
        categorie: "dure",
        sapNaoh: 0.195,
        sapKoh: 0.274,
        iode: 76.0,
        ins: 119.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 9.0,
        stearique: 5.0,
        ricinoleique: 0.0,
        oleique: 59.0,
        linoleique: 2.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL. Huile stable, proche de l’olive avec meilleure pénétration. Convient très bien aux peaux sensibles.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre de mafura",
        categorie: "dure",
        sapNaoh: 0.198,
        sapKoh: 0.278,
        iode: 66.0,
        ins: 132.0,
        laurique: 0.0,
        myristique: 1.0,
        palmitique: 37.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 49.0,
        linoleique: 11.0,
        linolenique: 1.0,
        commentaire: "Sources : FNWL. Beurre traditionnel africain, très riche en palmitique. Bon compromis entre dureté et nutrition.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre de mangue",
        categorie: "dure",
        sapNaoh: 0.191,
        sapKoh: 0.268,
        iode: 45.0,
        ins: 146.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 7.0,
        stearique: 42.0,
        ricinoleique: 0.0,
        oleique: 45.0,
        linoleique: 3.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, AAK. Beurre très stable et dur, comparable au karité avec texture plus sèche.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de noyau de mangue",
        categorie: "dure",
        sapNaoh: 0.190,
        sapKoh: 0.267,
        iode: 60.0,
        ins: 130.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 8.0,
        stearique: 27.0,
        ricinoleique: 0.0,
        oleique: 52.0,
        linoleique: 8.0,
        linolenique: 1.0,
        commentaire: "Sources : FNWL, AAK. Variante plus fondante du beurre de mangue. Bon équilibre dureté/émollience.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de marula",
        categorie: "douce",
        sapNaoh: 0.192,
        sapKoh: 0.270,
        iode: 73.0,
        ins: 119.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 11.0,
        stearique: 7.0,
        ricinoleique: 0.0,
        oleique: 75.0,
        linoleique: 4.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, MakingCosmetics. Riche en oléique, très stable. Bonne alternative à l’olive en SAF.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de limnanthe",
        categorie: "douce",
        sapNaoh: 0.169,
        sapKoh: 0.237,
        iode: 92.0,
        ins: 77.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 3.0,
        stearique: 0.0,
        ricinoleique: 0.0,
        oleique: 60.0,
        linoleique: 0.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL. Huile rare très stable, riche en AG longue chaîne. Excellente pour peaux sensibles.",
        fiabilite: "confirmée"
    },
    {
        nom: "Matière grasse laitière",
        categorie: "dure",
        sapNaoh: 0.227,
        sapKoh: 0.318,
        iode: 30.0,
        ins: 191.0,
        laurique: 4.0,
        myristique: 11.0,
        palmitique: 28.0,
        stearique: 12.0,
        ricinoleique: 0.0,
        oleique: 19.0,
        linoleique: 2.0,
        linolenique: 1.0,
        commentaire: "Sources : SoapCalc, USDA. Profil riche en AG saturés laitiers. Excellent durcisseur, mousse crémeuse.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de chardon-Marie",
        categorie: "douce",
        sapNaoh: 0.196,
        sapKoh: 0.275,
        iode: 115.0,
        ins: 81.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 7.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 26.0,
        linoleique: 64.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL. Très bon émollient riche en linoleique. Fragile en SAF, à utiliser avec prudence.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de monoï de Tahiti",
        categorie: "dure",
        sapNaoh: 0.255,
        sapKoh: 0.358,
        iode: 9.0,
        ins: 246.0,
        laurique: 44.0,
        myristique: 16.0,
        palmitique: 10.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 6.0,
        linoleique: 2.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc. Infusion de fleurs de tiaré dans huile de coco. Parfumé naturellement. Très moussant.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de moringa",
        categorie: "douce",
        sapNaoh: 0.192,
        sapKoh: 0.269,
        iode: 68.0,
        ins: 124.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 7.0,
        stearique: 7.0,
        ricinoleique: 0.0,
        oleique: 71.0,
        linoleique: 2.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, SoapCalc. Huile stable, très riche en oléique. Idéale pour peaux sensibles ou sèches.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre de mowrah",
        categorie: "dure",
        sapNaoh: 0.194,
        sapKoh: 0.272,
        iode: 62.0,
        ins: 132.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 24.0,
        stearique: 22.0,
        ricinoleique: 0.0,
        oleique: 36.0,
        linoleique: 15.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL. Beurre peu connu, excellent durcisseur doux, proche du karité.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre de murumuru",
        categorie: "dure",
        sapNaoh: 0.275,
        sapKoh: 0.386,
        iode: 25.0,
        ins: 250.0,
        laurique: 47.0,
        myristique: 26.0,
        palmitique: 6.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 15.0,
        linoleique: 3.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL. Beurre très dur, très moussant, idéal pour savons solides et barres capillaires.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de moutarde",
        categorie: "douce",
        sapNaoh: 0.173,
        sapKoh: 0.243,
        iode: 101.0,
        ins: 72.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 2.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 18.0,
        linoleique: 14.0,
        linolenique: 9.0,
        commentaire: "Sources : FNWL. Stimule la circulation, parfois irritante. À intégrer en très faible dose dans les savons énergisants.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre de muscade",
        categorie: "dure",
        sapNaoh: 0.1624,
        sapKoh: 0.228,
        iode: 46.0,
        ins: 116.0,
        laurique: 3.0,
        myristique: 83.0,
        palmitique: 4.0,
        stearique: 0.0,
        ricinoleique: 0.0,
        oleique: 5.0,
        linoleique: 0.0,
        linolenique: 0.0,
        commentaire: "Sources : FAO, FNWL. Très riche en myristique, fond très rapidement. Usage rare, mais intéressant pour fondants et savons moussants.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile d’avoine",
        categorie: "douce",
        sapNaoh: 0.190,
        sapKoh: 0.267,
        iode: 104.0,
        ins: 86.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 15.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 40.0,
        linoleique: 39.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL. Très douce, apaisante, bonne pour les peaux sensibles. Excellente synergie avec avoine colloïdale.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile d’olive",
        categorie: "dure",
        sapNaoh: 0.190,
        sapKoh: 0.266,
        iode: 85.0,
        ins: 105.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 14.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 69.0,
        linoleique: 12.0,
        linolenique: 1.0,
        commentaire: "Sources : SoapCalc, FNWL. Huile de base très stable. Idéale pour peaux sensibles. Référence du savon de Castille.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de grignons d’olive",
        categorie: "dure",
        sapNaoh: 0.188,
        sapKoh: 0.264,
        iode: 84.0,
        ins: 104.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 14.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 69.0,
        linoleique: 12.0,
        linolenique: 2.0,
        commentaire: "Sources : SoapCalc, FAO. Version extraite par solvant des résidus d’olive. Moins noble mais mêmes propriétés en SAF.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de graine de papaye",
        categorie: "dure",
        sapNaoh: 0.158,
        sapKoh: 0.222,
        iode: 67.0,
        ins: 91.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 13.0,
        stearique: 5.0,
        ricinoleique: 0.0,
        oleique: 76.0,
        linoleique: 3.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, SoapCalc. Huile très stable, excellente glisse. Intéressante pour savons de rasage ou peau sensible.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de graine de fruit de la passion",
        categorie: "douce",
        sapNaoh: 0.183,
        sapKoh: 0.257,
        iode: 136.0,
        ins: 47.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 10.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 15.0,
        linoleique: 70.0,
        linolenique: 1.0,
        commentaire: "Sources : FNWL. Huile très riche en AG polyinsaturés, fragile à l’oxydation. À limiter à faible dose en SAF.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de pataua",
        categorie: "dure",
        sapNaoh: 0.200,
        sapKoh: 0.281,
        iode: 77.0,
        ins: 123.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 13.0,
        stearique: 4.0,
        ricinoleique: 0.0,
        oleique: 78.0,
        linoleique: 3.0,
        linolenique: 1.0,
        commentaire: "Sources : FNWL. Profil exceptionnellement stable et nourrissant. Très bon choix pour savons visage.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de noyau de pêche",
        categorie: "douce",
        sapNaoh: 0.191,
        sapKoh: 0.268,
        iode: 108.0,
        ins: 87.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 6.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 65.0,
        linoleique: 25.0,
        linolenique: 1.0,
        commentaire: "Sources : SoapCalc, FNWL. Très proche de l’amande douce, bien tolérée et stable. Bonne huile de base en SAF doux.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile d’arachide",
        categorie: "douce",
        sapNaoh: 0.192,
        sapKoh: 0.270,
        iode: 92.0,
        ins: 99.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 8.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 56.0,
        linoleique: 26.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, USDA. Huile stable et équilibrée, mais allergène potentiel. Utilisation prudente en cosmétique.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de pistache",
        categorie: "douce",
        sapNaoh: 0.186,
        sapKoh: 0.261,
        iode: 95.0,
        ins: 92.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 11.0,
        stearique: 1.0,
        ricinoleique: 0.0,
        oleique: 63.0,
        linoleique: 25.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL. Assez stable, très émolliente, peu utilisée. Bon substitut aux huiles de noyaux.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de noyau de prune",
        categorie: "douce",
        sapNaoh: 0.194,
        sapKoh: 0.272,
        iode: 98.0,
        ins: 96.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 3.0,
        stearique: 0.0,
        ricinoleique: 0.0,
        oleique: 68.0,
        linoleique: 23.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL. Parfum naturel d’amande. Très stable, très bien tolérée en SAF et soins du visage.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de graine de grenade",
        categorie: "douce",
        sapNaoh: 0.190,
        sapKoh: 0.267,
        iode: 22.0,
        ins: 168.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 3.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 7.0,
        linoleique: 10.0,
        linolenique: 70.0,
        commentaire: "Sources : FNWL. Très riche en punicique (type linolénique). Ultra fragile, usage en surgras uniquement.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de graine de pracaxi",
        categorie: "dure",
        sapNaoh: 0.175,
        sapKoh: 0.246,
        iode: 68.0,
        ins: 107.0,
        laurique: 1.0,
        myristique: 1.0,
        palmitique: 2.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 44.0,
        linoleique: 2.0,
        linolenique: 2.0,
        commentaire: "Sources : FNWL. Excellente glisse, propriétés démêlantes, proche de l’huile de brocoli. Bonne stabilité.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de graine de citrouille",
        categorie: "douce",
        sapNaoh: 0.195,
        sapKoh: 0.274,
        iode: 128.0,
        ins: 67.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 11.0,
        stearique: 8.0,
        ricinoleique: 0.0,
        oleique: 33.0,
        linoleique: 50.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL. Riche en zinc naturel. Bon effet apaisant. Stabilité moyenne en SAF.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de colza non raffinée",
        categorie: "douce",
        sapNaoh: 0.175,
        sapKoh: 0.246,
        iode: 106.0,
        ins: 69.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 4.0,
        stearique: 1.0,
        ricinoleique: 0.0,
        oleique: 60.0,
        linoleique: 20.0,
        linolenique: 9.0,
        commentaire: "Sources : SoapCalc, FNWL. Profil équilibré et stable en SAF si non chauffé excessivement. Bon substitut à l’olive.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de graine de framboise",
        categorie: "douce",
        sapNaoh: 0.187,
        sapKoh: 0.262,
        iode: 163.0,
        ins: 24.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 3.0,
        stearique: 0.0,
        ricinoleique: 0.0,
        oleique: 13.0,
        linoleique: 55.0,
        linolenique: 26.0,
        commentaire: "Sources : FNWL, MakingCosmetics. Très riche en AG essentiels. Usage en SAF limité à 5 % max, idéal en surgras.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de son de riz",
        categorie: "douce",
        sapNaoh: 0.187,
        sapKoh: 0.262,
        iode: 100.0,
        ins: 87.0,
        laurique: 0.0,
        myristique: 1.0,
        palmitique: 22.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 38.0,
        linoleique: 34.0,
        linolenique: 2.0,
        commentaire: "Sources : SoapCalc, FNWL. Douce, équilibrée et très bien tolérée. Apporte onctuosité et stabilité.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de carthame HO",
        categorie: "douce",
        sapNaoh: 0.190,
        sapKoh: 0.267,
        iode: 93.0,
        ins: 97.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 5.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 77.0,
        linoleique: 15.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, SoapCalc. Variante haute en oléique, bien plus stable que le carthame classique. Excellente pour SAF.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre de sal",
        categorie: "dure",
        sapNaoh: 0.185,
        sapKoh: 0.260,
        iode: 39.0,
        ins: 146.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 6.0,
        stearique: 44.0,
        ricinoleique: 0.0,
        oleique: 40.0,
        linoleique: 2.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, AAK. Très structurant, proche du karité avec texture plus dense. Idéal pour savons solides.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de graine d’argousier",
        categorie: "douce",
        sapNaoh: 0.195,
        sapKoh: 0.274,
        iode: 165.0,
        ins: 30.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 7.0,
        stearique: 3.0,
        ricinoleique: 0.0,
        oleique: 14.0,
        linoleique: 36.0,
        linolenique: 38.0,
        commentaire: "Sources : FNWL. Très concentrée en oméga-3/6/9. Utilisation exclusivement en surgras post-SAF (<5 %).",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de graine et de baie d’argousier",
        categorie: "dure",
        sapNaoh: 0.183,
        sapKoh: 0.257,
        iode: 86.0,
        ins: 97.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 30.0,
        stearique: 1.0,
        ricinoleique: 0.0,
        oleique: 28.0,
        linoleique: 10.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL. Profil beaucoup plus saturé que l’huile de graines seule. Convient en SAF à faible dose.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de sésame",
        categorie: "douce",
        sapNaoh: 0.188,
        sapKoh: 0.264,
        iode: 110.0,
        ins: 81.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 10.0,
        stearique: 5.0,
        ricinoleique: 0.0,
        oleique: 40.0,
        linoleique: 43.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL. Bonne huile équilibrée et pénétrante. Relativement stable pour une huile riche en linoleique.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre de karité",
        categorie: "dure",
        sapNaoh: 0.179,
        sapKoh: 0.251,
        iode: 59.0,
        ins: 116.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 5.0,
        stearique: 40.0,
        ricinoleique: 0.0,
        oleique: 48.0,
        linoleique: 6.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL, AAK. Beurre polyvalent, très nourrissant et protecteur. Incontournable en formulation artisanale.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de tournesol à HO",
        categorie: "douce",
        sapNaoh: 0.189,
        sapKoh: 0.265,
        iode: 83.0,
        ins: 106.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 3.0,
        stearique: 4.0,
        ricinoleique: 0.0,
        oleique: 83.0,
        linoleique: 4.0,
        linolenique: 1.0,
        commentaire: "Sources : SoapCalc, FNWL. Huile locale stable, douce et très bien tolérée. Excellente base pour SAF doux.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de tamanu (kamani)",
        categorie: "douce",
        sapNaoh: 0.208,
        sapKoh: 0.292,
        iode: 111.0,
        ins: 82.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 12.0,
        stearique: 13.0,
        ricinoleique: 0.0,
        oleique: 34.0,
        linoleique: 38.0,
        linolenique: 1.0,
        commentaire: "Sources : FNWL. Huile réparatrice, anti-inflammatoire. Usage recommandé à faible dose pour soins ciblés.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre de graine de tucuma",
        categorie: "dure",
        sapNaoh: 0.238,
        sapKoh: 0.334,
        iode: 13.0,
        ins: 175.0,
        laurique: 48.0,
        myristique: 23.0,
        palmitique: 6.0,
        stearique: 0.0,
        ricinoleique: 0.0,
        oleique: 13.0,
        linoleique: 0.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, SoapCalc. Très dur et très moussant. Idéal pour savons solides ou barres capillaires.",
        fiabilite: "confirmée"
    },
    {
        nom: "Beurre d’ucuuba",
        categorie: "dure",
        sapNaoh: 0.205,
        sapKoh: 0.288,
        iode: 38.0,
        ins: 167.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 0.0,
        stearique: 31.0,
        ricinoleique: 0.0,
        oleique: 44.0,
        linoleique: 5.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL. Beurre très structurant avec haut taux de stéarique. Texture sèche, durcisseur efficace.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de noix",
        categorie: "douce",
        sapNaoh: 0.189,
        sapKoh: 0.265,
        iode: 145.0,
        ins: 45.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 7.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 18.0,
        linoleique: 60.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL. Très instable, à réserver aux soins post-SAF ou surgras à froid. Antioxydants indispensables.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de graine de pastèque",
        categorie: "douce",
        sapNaoh: 0.190,
        sapKoh: 0.267,
        iode: 119.0,
        ins: 71.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 11.0,
        stearique: 10.0,
        ricinoleique: 0.0,
        oleique: 18.0,
        linoleique: 60.0,
        linolenique: 1.0,
        commentaire: "Sources : FNWL. Riche en linoleique, mais assez équilibrée. Bonne synergie avec huiles plus saturées.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de germe de blé",
        categorie: "douce",
        sapNaoh: 0.183,
        sapKoh: 0.257,
        iode: 128.0,
        ins: 58.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 17.0,
        stearique: 2.0,
        ricinoleique: 0.0,
        oleique: 17.0,
        linoleique: 58.0,
        linolenique: 0.0,
        commentaire: "Sources : SoapCalc, FNWL. Riche en vitamine E et AG essentiels. Très instable en SAF, à réserver au surgras ou soins post-cure.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de yangu (châtaignier du Cap)",
        categorie: "douce",
        sapNaoh: 0.192,
        sapKoh: 0.269,
        iode: 95.0,
        ins: 97.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 18.0,
        stearique: 5.0,
        ricinoleique: 0.0,
        oleique: 45.0,
        linoleique: 30.0,
        linolenique: 1.0,
        commentaire: "Sources : FNWL. Huile africaine douce, équilibrée, stabilisante. Bon choix en savon pour peaux mixtes ou cheveux.",
        fiabilite: "confirmée"
    },
    {
        nom: "Huile de graine de sapote (sapuyul ou mamey)",
        categorie: "douce",
        sapNaoh: 0.188,
        sapKoh: 0.264,
        iode: 72.0,
        ins: 116.0,
        laurique: 0.0,
        myristique: 0.0,
        palmitique: 9.0,
        stearique: 21.0,
        ricinoleique: 0.0,
        oleique: 52.0,
        linoleique: 13.0,
        linolenique: 0.0,
        commentaire: "Sources : FNWL, MakingCosmetics. Huile douce et stable, avec profil très adapté aux peaux réactives ou cuir chevelu.",
        fiabilite: "confirmée"
    }

];
